
version: "2"

services:
  pgbackups:
    image: myros/postgres-backup
    volumes:
      - ./backups/pg:/backups

    environment:
      DUMPPREFIX: pg_
      PG_USER: docker
      PG_PASSWORD: docker
      PG_PORT: 5432
      PG_HOST: postgres
      PG_DB: database1; database2
      PG_EXTRA_OPTS: "-w -Fc"
      SCHEDULE: "@every 6h"
      SLACK_CHANNEL: "backups"
      SLACK_HOST: "https://hooks.slack.com/services/YOUR_DATA"

networks:
  default:
    external:
      name: NAME_OF_YOUR_POSTGRES_NETWORK
